import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';

test('catalogue and concern filters acknowledge changes and stay reversible', async () => {
  const root = process.cwd();
  const catalogue = await readFile(path.join(root, 'app/(site)/products/page.tsx'), 'utf8');
  const feedback = await readFile(path.join(root, 'components/products/filter-feedback-actions.tsx'), 'utf8');
  const tracker = await readFile(path.join(root, 'components/products/catalogue-transition-tracker.tsx'), 'utf8');
  const sheet = await readFile(path.join(root, 'components/products/inventory-filter-sheet.tsx'), 'utf8');
  const search = await readFile(path.join(root, 'components/products/catalogue-search.tsx'), 'utf8');
  const searchStyles = await readFile(path.join(root, 'components/products/catalogue-search.module.css'), 'utf8');
  const concerns = await readFile(path.join(root, 'components/concerns/concern-selector.tsx'), 'utf8');
  const concernsPage = await readFile(path.join(root, 'app/(site)/concerns/page.tsx'), 'utf8');
  const concernGuide = await readFile(path.join(root, 'app/(site)/concerns/[slug]/page.tsx'), 'utf8');
  const productPanel = await readFile(path.join(root, 'components/products/product-quick-panel.tsx'), 'utf8');
  const navigation = await readFile(path.join(root, 'components/navigation/site-header.tsx'), 'utf8');
  const layout = await readFile(path.join(root, 'app/(site)/layout.tsx'), 'utf8');
  const catalogueStyles = await readFile(path.join(root, 'app/(site)/products/products.module.css'), 'utf8');
  const catalogueMotion = await readFile(path.join(root, 'app/(site)/products/catalogue-feedback.module.css'), 'utf8');
  const concernMotion = await readFile(path.join(root, 'components/concerns/concern-feedback.module.css'), 'utf8');

  assert.match(feedback, /role="status" aria-live="polite"/);
  assert.match(feedback, /catalogueTransitionMessage/);
  assert.match(feedback, /data-catalogue-transition-kind="undo"/);
  assert.match(tracker, /sessionStorage/);
  assert.match(catalogue, /CatalogueTransitionTracker/);
  assert.match(catalogue, /!hasActiveIntent/);
  assert.match(catalogue, /matchingCatalogueConcerns/);
  assert.match(catalogue, /#all-products/);
  assert.match(catalogue, /CatalogueSearch/);
  assert.match(catalogue, /\['category', 'routine', 'concern'\]/);
  assert.match(catalogue, /result\.facets\.steps/);
  assert.match(catalogue, /marketHrefs=\{marketHrefs\}/);
  assert.match(search, /role="combobox"/);
  assert.match(search, /aria-activedescendant/);
  assert.match(search, /role="listbox"/);
  assert.match(search, /role="status" aria-live="polite"/);
  assert.match(search, /recordCatalogueTransition/);
  assert.match(search, /href=\{marketHrefs\.NG\}/);
  assert.match(search, /href=\{marketHrefs\.US\}/);
  assert.match(searchStyles, /@media \(max-width: 640px\)[\s\S]*position: fixed/);
  assert.match(searchStyles, /\.shell\s*\{[\s\S]*position: sticky;[\s\S]*top: 5\.35rem;/);
  assert.match(searchStyles, /@media \(max-width: 640px\)[\s\S]*\.shell\s*\{[\s\S]*position: relative;[\s\S]*top: auto;/);
  assert.match(searchStyles, /scrollbar-width: none/);
  assert.match(catalogueStyles, /^\.page\{overflow:clip;/);
  assert.doesNotMatch(search, /[😀-🙏]/u);
  assert.equal((sheet.match(/<dialog/g) ?? []).length, 1);
  assert.doesNotMatch(sheet, /datalist|companyLogo|avatar/i);
  assert.match(sheet, /count > 0 \|\| filters\.category === value/);
  assert.match(sheet, /count > 0 \|\| filters\.review === value/);
  assert.match(sheet, /Search companies/);
  assert.match(concerns, /role="status" aria-live="polite"/);
  assert.match(concerns, /Last change undone/);
  assert.match(concerns, /View matches/);
  assert.match(concerns, /Selections cleared/);
  assert.match(concerns, /!isProductMatchConcern\(concern\)/);
  assert.match(concerns, /guideCardLink/);
  assert.match(concernsPage, /filter\(isProductMatchConcern\)/);
  assert.match(concernGuide, /condition-pattern[\s\S]*Browse concerns/);
  assert.match(productPanel, /Find a store/);
  assert.match(productPanel, /How to use/);
  assert.doesNotMatch(productPanel, /Check the pack before use/);
  assert.doesNotMatch(productPanel, /Buy options|See prices/);
  assert.match(navigation, /href="\/contribute"[^>]*>Share skincare/);
  assert.match(navigation, /label: 'Share skincare', detail: 'Tell us what you use'/);
  assert.match(layout, /href="\/contribute">Share skincare/);
  assert.match(catalogueMotion, /prefers-reduced-motion/);
  assert.match(concernMotion, /prefers-reduced-motion/);
});
