import type { IngredientKnowledge } from "./types";

export const ingredientKnowledge: IngredientKnowledge[] = [
  {
    id: "salicylic-acid",
    name: "Salicylic acid",
    aliases: ["salicylic acid", "bha"],
    family: "exfoliant",
    evidence: "high",
    concerns: ["acne", "blackheads", "oiliness", "congestion"],
    allowedTimes: ["morning", "evening"],
    pregnancy: "caution",
    breastfeeding: "safe",
    photosensitivity: "low",
    irritationRisk: "moderate",
  },
  {
    id: "glycolic-acid",
    name: "Glycolic acid",
    aliases: ["glycolic acid", "aha"],
    family: "exfoliant",
    evidence: "high",
    concerns: ["texture", "hyperpigmentation"],
    allowedTimes: ["evening", "weekly"],
    pregnancy: "caution",
    breastfeeding: "safe",
    photosensitivity: "moderate",
    irritationRisk: "high",
  },
  {
    id: "retinol",
    name: "Retinol",
    aliases: ["retinol", "retinoid", "retinal"],
    family: "retinoid",
    evidence: "high",
    concerns: ["acne", "texture", "fine lines", "hyperpigmentation"],
    allowedTimes: ["evening"],
    pregnancy: "avoid",
    breastfeeding: "caution",
    photosensitivity: "moderate",
    irritationRisk: "high",
  },
  {
    id: "tretinoin",
    name: "Tretinoin",
    aliases: ["tretinoin", "retin-a"],
    family: "retinoid",
    evidence: "high",
    concerns: ["acne", "photoaging", "hyperpigmentation"],
    allowedTimes: ["evening"],
    pregnancy: "avoid",
    breastfeeding: "caution",
    photosensitivity: "moderate",
    irritationRisk: "high",
  },
  {
    id: "benzoyl-peroxide",
    name: "Benzoyl peroxide",
    aliases: ["benzoyl peroxide", "bpo"],
    family: "antimicrobial",
    evidence: "high",
    concerns: ["acne", "inflamed spots"],
    allowedTimes: ["morning", "evening"],
    pregnancy: "safe",
    breastfeeding: "caution",
    photosensitivity: "low",
    irritationRisk: "high",
  },
  {
    id: "azelaic-acid",
    name: "Azelaic acid",
    aliases: ["azelaic acid"],
    family: "brightening",
    evidence: "high",
    concerns: ["acne", "hyperpigmentation", "redness"],
    allowedTimes: ["morning", "evening"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "none",
    irritationRisk: "low",
  },
  {
    id: "niacinamide",
    name: "Niacinamide",
    aliases: ["niacinamide", "nicotinamide", "vitamin b3"],
    family: "barrier",
    evidence: "high",
    concerns: ["oiliness", "barrier", "hyperpigmentation"],
    allowedTimes: ["morning", "evening"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "none",
    irritationRisk: "low",
  },
  {
    id: "tranexamic-acid",
    name: "Tranexamic acid",
    aliases: ["tranexamic acid", "txa"],
    family: "brightening",
    evidence: "moderate",
    concerns: ["hyperpigmentation", "dark spots"],
    allowedTimes: ["morning", "evening"],
    pregnancy: "unknown",
    breastfeeding: "unknown",
    photosensitivity: "none",
    irritationRisk: "low",
  },
  {
    id: "ceramides",
    name: "Ceramides",
    aliases: ["ceramide", "ceramides"],
    family: "barrier",
    evidence: "high",
    concerns: ["barrier", "dryness", "sensitivity"],
    allowedTimes: ["morning", "evening", "any"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "none",
    irritationRisk: "low",
  },
  {
    id: "sunscreen",
    name: "Broad-spectrum sunscreen",
    aliases: ["sunscreen", "spf", "uv protection"],
    family: "sunscreen",
    evidence: "high",
    concerns: ["hyperpigmentation", "photoaging", "sun protection"],
    allowedTimes: ["morning"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "none",
    irritationRisk: "low",
  },
  {
    id: "lactic-acid",
    name: "Lactic acid",
    aliases: ["lactic acid", "aha"],
    family: "exfoliant",
    evidence: "high",
    concerns: ["texture", "hyperpigmentation", "dryness"],
    allowedTimes: ["evening", "weekly"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "moderate",
    irritationRisk: "moderate",
  },
  {
    id: "mandelic-acid",
    name: "Mandelic acid",
    aliases: ["mandelic acid"],
    family: "exfoliant",
    evidence: "moderate",
    concerns: ["acne", "texture", "hyperpigmentation"],
    allowedTimes: ["evening", "weekly"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "low",
    irritationRisk: "low",
  },
  {
    id: "ascorbic-acid",
    name: "L-Ascorbic acid",
    aliases: ["ascorbic acid", "l-ascorbic acid", "vitamin c", "l-ascorbic"],
    family: "brightening",
    evidence: "high",
    concerns: ["hyperpigmentation", "photoaging", "dark spots"],
    allowedTimes: ["morning"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "none",
    irritationRisk: "low",
  },
  {
    id: "tocopherol",
    name: "Vitamin E",
    aliases: ["tocopherol", "vitamin e", "alpha-tocopherol"],
    family: "barrier",
    evidence: "moderate",
    concerns: ["barrier", "dryness", "photoaging"],
    allowedTimes: ["morning", "evening", "any"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "none",
    irritationRisk: "low",
  },
  {
    id: "hyaluronic-acid",
    name: "Hyaluronic acid",
    aliases: ["hyaluronic acid", "sodium hyaluronate", "ha"],
    family: "hydrating",
    evidence: "high",
    concerns: ["dryness", "barrier"],
    allowedTimes: ["morning", "evening", "any"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "none",
    irritationRisk: "low",
  },
  {
    id: "glycerin",
    name: "Glycerin",
    aliases: ["glycerin", "glycerine", "glycerol"],
    family: "hydrating",
    evidence: "high",
    concerns: ["dryness", "barrier"],
    allowedTimes: ["morning", "evening", "any"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "none",
    irritationRisk: "low",
  },
  {
    id: "panthenol",
    name: "Panthenol",
    aliases: ["panthenol", "provitamin b5", "dexpanthenol", "pantothenic acid"],
    family: "barrier",
    evidence: "moderate",
    concerns: ["barrier", "dryness", "sensitivity"],
    allowedTimes: ["morning", "evening", "any"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "none",
    irritationRisk: "low",
  },
  {
    id: "allantoin",
    name: "Allantoin",
    aliases: ["allantoin"],
    family: "barrier",
    evidence: "moderate",
    concerns: ["barrier", "sensitivity"],
    allowedTimes: ["morning", "evening", "any"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "none",
    irritationRisk: "low",
  },
  {
    id: "centella-asiatica",
    name: "Centella asiatica",
    aliases: [
      "centella asiatica",
      "cica",
      "gotu kola",
      "asiaticoside",
      "madecassoside",
    ],
    family: "barrier",
    evidence: "moderate",
    concerns: ["barrier", "sensitivity", "redness"],
    allowedTimes: ["morning", "evening", "any"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "none",
    irritationRisk: "low",
  },
  {
    id: "zinc-oxide",
    name: "Zinc oxide",
    aliases: ["zinc oxide", "zno"],
    family: "sunscreen",
    evidence: "high",
    concerns: ["sun protection", "photoaging", "redness"],
    allowedTimes: ["morning"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "none",
    irritationRisk: "low",
  },
  {
    id: "sulfur",
    name: "Sulfur",
    aliases: ["sulfur", "sulphur"],
    family: "antimicrobial",
    evidence: "moderate",
    concerns: ["acne", "oiliness"],
    allowedTimes: ["morning", "evening", "weekly"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "none",
    irritationRisk: "moderate",
  },
  {
    id: "kojic-acid",
    name: "Kojic acid",
    aliases: ["kojic acid"],
    family: "brightening",
    evidence: "moderate",
    concerns: ["hyperpigmentation", "dark spots"],
    allowedTimes: ["evening"],
    pregnancy: "caution",
    breastfeeding: "caution",
    photosensitivity: "moderate",
    irritationRisk: "moderate",
  },
  {
    id: "licorice-root",
    name: "Licorice root extract",
    aliases: ["licorice", "glycyrrhiza", "glabridin", "glycyrrhizic acid"],
    family: "brightening",
    evidence: "moderate",
    concerns: ["hyperpigmentation", "dark spots", "redness"],
    allowedTimes: ["morning", "evening"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "none",
    irritationRisk: "low",
  },
  {
    id: "caffeine",
    name: "Caffeine",
    aliases: ["caffeine"],
    family: "other",
    evidence: "moderate",
    concerns: ["redness", "photoaging"],
    allowedTimes: ["morning", "evening"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "none",
    irritationRisk: "low",
  },
  {
    id: "urea",
    name: "Urea",
    aliases: ["urea"],
    family: "hydrating",
    evidence: "high",
    concerns: ["dryness", "barrier", "texture"],
    allowedTimes: ["morning", "evening", "any"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "none",
    irritationRisk: "low",
  },
  {
    id: "squalane",
    name: "Squalane",
    aliases: ["squalane", "squalene"],
    family: "barrier",
    evidence: "moderate",
    concerns: ["dryness", "barrier"],
    allowedTimes: ["morning", "evening", "any"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "none",
    irritationRisk: "low",
  },
  {
    id: "tea-tree-oil",
    name: "Tea tree oil",
    aliases: ["tea tree oil", "melaleuca", "tea tree"],
    family: "antimicrobial",
    evidence: "moderate",
    concerns: ["acne"],
    allowedTimes: ["morning", "evening"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "none",
    irritationRisk: "moderate",
  },
  {
    id: "adapalene",
    name: "Adapalene",
    aliases: ["adapalene", "differin"],
    family: "retinoid",
    evidence: "high",
    concerns: ["acne", "blackheads"],
    allowedTimes: ["evening"],
    pregnancy: "avoid",
    breastfeeding: "caution",
    photosensitivity: "moderate",
    irritationRisk: "high",
  },
  {
    id: "bakuchiol",
    name: "Bakuchiol",
    aliases: ["bakuchiol"],
    family: "other",
    evidence: "limited",
    concerns: ["photoaging", "texture", "fine lines"],
    allowedTimes: ["morning", "evening"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "none",
    irritationRisk: "low",
  },
  {
    id: "gluconolactone",
    name: "Gluconolactone",
    aliases: ["gluconolactone", "pha"],
    family: "exfoliant",
    evidence: "moderate",
    concerns: ["texture", "sensitivity", "dryness"],
    allowedTimes: ["morning", "evening", "weekly"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "low",
    irritationRisk: "low",
  },
  {
    id: "peptides",
    name: "Peptides",
    aliases: ["peptide", "peptides", "matrixyl", "arginine", "copper peptide"],
    family: "other",
    evidence: "moderate",
    concerns: ["photoaging", "barrier", "fine lines"],
    allowedTimes: ["morning", "evening"],
    pregnancy: "safe",
    breastfeeding: "safe",
    photosensitivity: "none",
    irritationRisk: "low",
  },
  {
    id: "hydroquinone",
    name: "Hydroquinone",
    aliases: ["hydroquinone"],
    family: "brightening",
    evidence: "high",
    concerns: ["hyperpigmentation", "dark spots"],
    allowedTimes: ["evening"],
    pregnancy: "avoid",
    breastfeeding: "avoid",
    photosensitivity: "high",
    irritationRisk: "high",
  },
];

export const ingredientById = new Map(
  ingredientKnowledge.map((ingredient) => [ingredient.id, ingredient]),
);

const medicineUseContext =
  /\b(?:tablet|tablets|capsule|capsules|pill|pills|oral(?:ly)?|medicine|medicines|medication|medications|prescription|prescribed|taking|i take|i took|dose|dosage|dosing)\b|\b(?:for|during)\s+(?:heavy\s+)?periods?\b|\bmenstrual bleeding\b/i;

export function hasMedicineUseContext(text: string) {
  return medicineUseContext.test(text);
}

export function detectIngredients(text: string) {
  const normalized = text.toLowerCase();
  return ingredientKnowledge.filter((ingredient) =>
    ingredient.aliases.some((alias) => normalized.includes(alias)),
  );
}
