/**
 * The concern lexicon maps free-text user descriptions to canonical concern
 * slugs. This is the semantic bridge between the user's own words and the
 * clinical knowledge base.
 *
 * Design principles:
 * - Deterministic: no ML, no embeddings. Term matching only.
 * - Conservative: when in doubt, return no concern rather than a wrong one.
 *   The consult engine will ask for clarification if no concern is matched.
 * - Inclusive: accept the many ways Nigerians actually describe skin concerns,
 *   including pidgin-influenced phrasing, brand-specific terms, and lay
 *   descriptions that a dermatologist would recognize but a user might not
 *   know the clinical name for.
 * - Auditable: every mapping is explicit and reviewable.
 *
 * This file is clinical authority. The consult route imports from here but
 * must never override the safety gate's deterministic decisions.
 */

export type ConcernLexiconEntry = {
  slug: string;
  terms: string[];
};

export const concernLexicon: Readonly<Record<string, string[]>> = {
  acne: [
    "acne",
    "pimple",
    "pimples",
    "breakout",
    "breakouts",
    "bumps",
    "whitehead",
    "whiteheads",
    "blackhead",
    "blackheads",
    "zit",
    "zits",
    "spot",
    "spots",
    "pustule",
    "pustules",
    "cyst",
    "cysts",
    "nodules",
    "papule",
    "papules",
    "inflamed bump",
    "painful bump",
    "blind pimple",
  ],
  blackheads: [
    "blackhead",
    "blackheads",
    "clogged",
    "clogged pore",
    "clogged pores",
    "congestion",
    "congested",
    "open comedo",
    "comedones",
    "dark bump",
    "tiny dark bump",
  ],
  oiliness: [
    "oily",
    "oiliness",
    "greasy",
    "grease",
    "shine",
    "shiny",
    "excess oil",
    "excess sebum",
    "sebum",
    "overproduction of oil",
    "my face gets oily",
    "oily by midday",
    "oily t-zone",
    "oily zone",
  ],
  hyperpigmentation: [
    "dark mark",
    "dark marks",
    "dark spot",
    "dark spots",
    "pigmentation",
    "uneven tone",
    "uneven skin tone",
    "melasma",
    "discoloration",
    "discolouration",
    "hyperpigmentation",
    "post-acne mark",
    "acne scar",
    "acne marks",
    "brown spot",
    "brown spots",
    "brown patch",
    "dark patch",
    "uneven complexion",
    "dullness",
  ],
  sensitivity: [
    "sensitive",
    "sensitivity",
    "burning",
    "stinging",
    "sting",
    "irritated",
    "irritation",
    "redness",
    "red",
    "reactive",
    "inflamed",
    "inflammation",
    "sore",
    "tender",
    "my skin reacts",
    "allergic reaction",
    "rash from product",
    "product irritation",
    "contact dermatitis",
    "over-exfoliated",
  ],
  dryness: [
    "dry",
    "dryness",
    "flaky",
    "flaking",
    "flake",
    "flakes",
    "scaly",
    "scale",
    "scales",
    "tight",
    "tightness",
    "dehydrated",
    "dehydration",
    "ashy",
    "ash",
    "rough",
    "roughness",
    "sandpaper",
  ],
  barrier: [
    "barrier",
    "skin barrier",
    "damaged barrier",
    "compromised barrier",
    "over-exfoliated",
    "overexfoliated",
    "burned my skin",
    "stripped",
    "skin feels raw",
    "raw skin",
    "moisture barrier",
    "acid mantle",
  ],
  dandruff: [
    "dandruff",
    "flaky scalp",
    "itchy scalp",
    "scalp flakes",
    "dry scalp",
    "scaly scalp",
    "cradle cap",
    "seborrheic dermatitis",
    "seborrhoeic dermatitis",
    "flakes in my hair",
    "white flakes",
  ],
  "dry hair": [
    "dry hair",
    "brittle hair",
    "frizz",
    "frizzy",
    "breakage",
    "breaking hair",
    "split ends",
    "rough hair",
    "coarse hair",
    "straw-like hair",
  ],
  texture: [
    "texture",
    "textured",
    "rough skin",
    "bumpy texture",
    "uneven texture",
    "smooth",
    "smoothing",
    "gritty",
    "grainy",
    "sandpaper skin",
    "strawberry legs",
    "chicken skin",
    "keratosis pilaris",
    "kp",
  ],
  "fine lines": [
    "fine line",
    "fine lines",
    "wrinkle",
    "wrinkles",
    "aging",
    "ageing",
    "anti-aging",
    "anti-ageing",
    "crows feet",
    "crow's feet",
    "laugh lines",
    "expression lines",
    "forehead lines",
    "sagging",
    "loss of firmness",
    "loss of elasticity",
  ],
  redness: [
    "redness",
    "red",
    "rosacea",
    "flushing",
    "flush",
    "persistent redness",
    "visible veins",
    "spider veins",
    "blushing",
    "red face",
    "red cheeks",
    "red nose",
  ],
  "dark circles": [
    "dark circle",
    "dark circles",
    "under eye",
    "under-eye",
    "eye bag",
    "eye bags",
    "bags under eyes",
    "tired eyes",
    "puffy eyes",
    "puffiness",
    "racoon eyes",
    "sunken eyes",
  ],
  "body breakouts": [
    "body acne",
    "back acne",
    "bacne",
    "chest acne",
    "body breakout",
    "body breakouts",
    "shoulder acne",
    "butt acne",
    "body bump",
    "body bumps",
  ],
  "hair loss": [
    "hair loss",
    "losing hair",
    "thinning hair",
    "receding",
    "balding",
    "bald spot",
    "alopecia",
    "shedding",
    "hair falling out",
    "hair breakage",
    "edges thinning",
    "traction alopecia",
    "postpartum hair loss",
  ],
  "scalp concerns": [
    "scalp pain",
    "scalp tenderness",
    "scalp sores",
    "scalp bumps",
    "scalp acne",
    "folliculitis",
    "ingrown hair",
    "ingrown hairs",
    "razor bump",
    "razor bumps",
    "pseudofolliculitis",
    "beard bump",
    "beard bumps",
  ],
  "sun protection": [
    "sunscreen",
    "sun protection",
    "spf",
    "uv",
    "sun damage",
    "sunburn",
    "sun burn",
    "sunspots",
    "sun spots",
    "photoaging",
    "photo-ageing",
    "photodamage",
  ],
};

export const concernLexiconEntries: ConcernLexiconEntry[] = Object.entries(
  concernLexicon,
).map(([slug, terms]) => ({ slug, terms }));

/**
 * Infer canonical concern slugs from free-text user input.
 * Returns concerns in the order they are found (first match wins per concern).
 * Empty array means no concern was matched — the consult engine should
 * ask for clarification.
 */
export function inferConcerns(query: string): string[] {
  const normalized = query.toLowerCase();
  return Object.entries(concernLexicon)
    .filter(([, terms]) => terms.some((term) => normalized.includes(term)))
    .map(([concern]) => concern);
}
